name: Build and push deps image
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  pull_request:
    branches: [ main ]
    paths:
      - docker/**
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: self-hosted
    strategy:
      matrix:
          architecture: [arm64]
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          github-sha: ${{ github.sha }}
          image-name: "ngen-deps"
          dockerfile-name: "Dockerfile.ngen-deps"
      - name: Publish slack message
        uses: ./.github/action_templates/slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job-status: ${{ job.status }}
          pull_request_url: ${{ github.event.pull_request.html_url }}
          head_commit_url: ${{ github.event.head_commit.url }}